// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhRJJUB-CUSci1yUFyMdVKONJo2z9Vm0w',
    appId: '1:1084123737823:android:e901d2fb30212b067b836a',
    messagingSenderId: '1084123737823',
    projectId: 'shopping-list-8820b',
    storageBucket: 'shopping-list-8820b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuc_agVdmmVoBUg6Sapp28KFV4CZ4s3Ps',
    appId: '1:1084123737823:ios:b6ecc919db61b3067b836a',
    messagingSenderId: '1084123737823',
    projectId: 'shopping-list-8820b',
    storageBucket: 'shopping-list-8820b.appspot.com',
    iosClientId: '1084123737823-s6pd29da6ke6odgfb9bda81dseb1te8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuc_agVdmmVoBUg6Sapp28KFV4CZ4s3Ps',
    appId: '1:1084123737823:ios:b6ecc919db61b3067b836a',
    messagingSenderId: '1084123737823',
    projectId: 'shopping-list-8820b',
    storageBucket: 'shopping-list-8820b.appspot.com',
    iosClientId: '1084123737823-s6pd29da6ke6odgfb9bda81dseb1te8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );
}
