name: shopping_app_core
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'


environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies_core:
    path: ../dependencies_core
  freezed: ^2.0.3+1
  cloud_firestore: ^3.1.17 
  fake_cloud_firestore: ^1.2.2
  firebase_storage: ^10.2.17 
  firebase_storage_mocks: ^0.5.0
  file_picker: ^4.6.0

  


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.2
  build_runner: ^2.1.11



flutter:
