name: design_system
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  statsfl: ^2.3.0 #Perfomance Monitoring
  #Loading
  loader_overlay: ^2.0.7 
  loading_animation_widget: ^1.2.0+1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/poppins/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/poppins/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/poppins/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/poppins/Poppins-Semibold.ttf
        weight: 600
      - asset: assets/fonts/poppins/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/poppins/Poppins-Black.ttf
        weight: 900